"""
PyTorch/MONAI conversion of labels_to_image_model.py

This function builds a PyTorch model to generate images from provided label maps.
The images are generated by sampling a Gaussian Mixture Model (of given parameters), conditioned on the label map.
"""

import torch
import torch.nn as nn
import numpy as np
from typing import Optional, List, Union, Tuple

# project imports
from ext.lab2im import utils_pytorch as utils
from ext.lab2im import edit_tensors_pytorch as l2i_et
from ext.lab2im.edit_volumes_pytorch import get_ras_axes
from . import layers_pytorch as layers


class LabelsToImageModel(nn.Module):
    """PyTorch model for generating synthetic images from label maps."""
    
    def __init__(self,
                 labels_shape: List[int],
                 n_channels: int,
                 generation_labels: np.ndarray,
                 output_labels: np.ndarray,
                 n_neutral_labels: int,
                 atlas_res: Union[float, List[float]],
                 target_res: Union[float, List[float]],
                 output_shape: Optional[List[int]] = None,
                 output_div_by_n: Optional[int] = None,
                 flipping: bool = True,
                 aff: Optional[np.ndarray] = None,
                 scaling_bounds: Union[float, List[float]] = 0.2,
                 rotation_bounds: Union[float, List[float]] = 15,
                 shearing_bounds: Union[float, List[float]] = 0.012,
                 translation_bounds: Union[bool, float, List[float]] = False,
                 nonlin_std: float = 3.,
                 nonlin_scale: float = .0625,
                 randomise_res: bool = False,
                 max_res_iso: float = 4.,
                 max_res_aniso: float = 8.,
                 data_res: Optional[Union[float, List[float]]] = None,
                 thickness: Optional[Union[float, List[float]]] = None,
                 bias_field_std: float = .5,
                 bias_scale: float = .025,
                 return_gradients: bool = False):
        
        super(LabelsToImageModel, self).__init__()
        
        # Store parameters
        self.labels_shape = labels_shape
        self.n_channels = n_channels
        self.generation_labels = generation_labels
        self.output_labels = output_labels
        self.n_neutral_labels = n_neutral_labels
        self.return_gradients = return_gradients
        
        # Reformat resolutions
        self.n_dims = len(labels_shape)
        self.atlas_res = utils.reformat_to_n_channels_array(atlas_res, self.n_dims, n_channels)
        self.data_res = self.atlas_res if data_res is None else utils.reformat_to_n_channels_array(data_res, self.n_dims, n_channels)
        self.thickness = self.data_res if thickness is None else utils.reformat_to_n_channels_array(thickness, self.n_dims, n_channels)
        self.atlas_res = self.atlas_res[0]
        self.target_res = self.atlas_res if target_res is None else utils.reformat_to_n_channels_array(target_res, self.n_dims)[0]
        
        # Get shapes
        self.crop_shape, self.output_shape = self._get_shapes(labels_shape, output_shape, self.atlas_res, self.target_res, output_div_by_n)
        
        # Initialize layers
        self._init_layers(
            scaling_bounds, rotation_bounds, shearing_bounds, translation_bounds,
            nonlin_std, nonlin_scale, flipping, aff, randomise_res,
            max_res_iso, max_res_aniso, bias_field_std, bias_scale
        )
    
    def _init_layers(self, scaling_bounds, rotation_bounds, shearing_bounds, translation_bounds,
                     nonlin_std, nonlin_scale, flipping, aff, randomise_res,
                     max_res_iso, max_res_aniso, bias_field_std, bias_scale):
        """Initialize all the transformation layers."""
        
        # Spatial deformation
        self.spatial_deform = layers.RandomSpatialDeformation(
            scaling_bounds=scaling_bounds,
            rotation_bounds=rotation_bounds,
            shearing_bounds=shearing_bounds,
            translation_bounds=translation_bounds,
            nonlin_std=nonlin_std,
            nonlin_scale=nonlin_scale,
            inter_method='nearest'
        )
        
        # Cropping
        if self.crop_shape != self.labels_shape:
            self.crop_layer = layers.RandomCrop(self.crop_shape)
        else:
            self.crop_layer = None
        
        # Flipping
        if flipping:
            assert aff is not None, 'aff should not be None if flipping is True'
            self.flip_layer = layers.RandomFlip(
                axis=get_ras_axes(aff, self.n_dims)[0],
                swap_labels=[True, False],  # swap labels, not image
                label_list=self.generation_labels,
                n_neutral_labels=self.n_neutral_labels
            )
        else:
            self.flip_layer = None
        
        # GMM sampling
        self.gmm_sampler = layers.SampleConditionalGMM(self.generation_labels)
        
        # Bias field corruption
        if bias_field_std > 0:
            self.bias_field = layers.BiasFieldCorruption(bias_field_std, bias_scale, False)
        else:
            self.bias_field = None
        
        # Intensity augmentation
        self.intensity_aug = layers.IntensityAugmentation(
            clip=300, normalise=True, gamma_std=.5, separate_channels=True
        )
        
        # Resolution randomization
        if randomise_res:
            self.sample_resolution = layers.SampleResolution(
                min_resolution=self.atlas_res,
                max_res_iso=max_res_iso,
                max_res_aniso=max_res_aniso
            )
            self.dynamic_blur = layers.DynamicGaussianBlur(
                max_sigma=0.75 * np.maximum(max_res_iso, max_res_aniso) / np.array(self.atlas_res),
                random_blur_range=1.03
            )
            self.mimic_acquisition = layers.MimicAcquisition(
                volume_res=self.atlas_res,
                min_subsample_res=self.atlas_res,
                resample_shape=self.output_shape if self.output_shape else self.labels_shape,
                build_dist_map=False
            )
        else:
            self.sample_resolution = None
            self.blur_layers = nn.ModuleList()
            self.mimic_layers = nn.ModuleList()
            
            for i in range(self.n_channels):
                sigma = l2i_et.blurring_sigma_for_downsampling(
                    self.atlas_res, self.data_res[i], thickness=self.thickness[i]
                )
                self.blur_layers.append(layers.GaussianBlur(sigma, 1.03))
                self.mimic_layers.append(layers.MimicAcquisition(
                    volume_res=self.atlas_res,
                    min_subsample_res=self.data_res[i],
                    resample_shape=self.output_shape if self.output_shape else self.labels_shape
                ))
        
        # Label conversion
        self.label_converter = layers.ConvertLabels(
            source_values=self.generation_labels,
            dest_values=self.output_labels
        )
        
        # Image gradients (if requested)
        if self.return_gradients:
            self.gradient_layer = layers.ImageGradients('sobel', True)
            self.gradient_intensity_aug = layers.IntensityAugmentation(
                clip=10, normalise=True
            )
    
    def forward(self, inputs):
        """
        Forward pass of the model.
        
        inputs: dict with keys:
            - 'labels': label map tensor (B, H, W, D) or (B, 1, H, W, D)
            - 'means': GMM means tensor (B, n_labels, n_channels)  
            - 'stds': GMM stds tensor (B, n_labels, n_channels)
        
        Returns:
            - generated image tensor
            - corresponding label map tensor
        """
        
        labels_input = inputs['labels']
        means_input = inputs['means'] 
        stds_input = inputs['stds']
        
        # Ensure labels have channel dimension
        if len(labels_input.shape) == len(self.labels_shape):
            labels_input = labels_input.unsqueeze(1)  # Add channel dimension
        
        # Apply spatial deformation to labels
        labels = self.spatial_deform(labels_input)
        
        # Apply cropping if needed
        if self.crop_layer is not None:
            labels = self.crop_layer(labels)
        
        # Apply flipping if enabled
        if self.flip_layer is not None:
            labels = self.flip_layer([labels])[0]  # Only flip labels, not means/stds
        
        # Generate synthetic image using GMM
        image = self.gmm_sampler([labels.squeeze(1), means_input, stds_input])
        
        # Add channel dimension to image if needed
        if len(image.shape) == len(self.labels_shape):
            image = image.unsqueeze(1)
        elif len(image.shape) == len(self.labels_shape) + 1 and self.n_channels > 1:
            # Rearrange to PyTorch format (B, C, spatial_dims)
            image = image.permute(0, -1, *range(1, len(image.shape)-1))
        
        # Apply bias field corruption
        if self.bias_field is not None:
            image = self.bias_field(image)
        
        # Apply intensity augmentation
        image = self.intensity_aug(image)
        
        # Process channels for resolution effects
        if self.n_channels > 1:
            channels = torch.chunk(image, self.n_channels, dim=1)
        else:
            channels = [image]
        
        processed_channels = []
        for i, channel in enumerate(channels):
            
            if self.sample_resolution is not None:
                # Dynamic resolution sampling
                resolution, blur_res = self.sample_resolution(means_input)
                sigma = l2i_et.blurring_sigma_for_downsampling(
                    self.atlas_res, resolution, thickness=blur_res
                )
                channel = self.dynamic_blur([channel, sigma])
                channel = self.mimic_acquisition([channel, resolution])
            else:
                # Fixed resolution processing
                channel = self.blur_layers[i](channel)
                resolution = torch.tensor(self.data_res[i], dtype=torch.float32, device=channel.device)
                resolution = resolution.unsqueeze(0).repeat(channel.shape[0], 1)
                channel = self.mimic_layers[i]([channel, resolution])
            
            processed_channels.append(channel)
        
        # Concatenate channels back
        if len(processed_channels) > 1:
            image = torch.cat(processed_channels, dim=1)
        else:
            image = processed_channels[0]
        
        # Compute image gradients if requested
        if self.return_gradients:
            image = self.gradient_layer(image)
            image = self.gradient_intensity_aug(image)
        
        # Resample labels to target resolution if needed
        if self.crop_shape != self.output_shape:
            labels = l2i_et.resample_tensor(labels, self.output_shape, interp_method='nearest')
        
        # Convert labels to output values
        labels_out = self.label_converter(labels)
        
        return {
            'image': image,
            'labels': labels_out
        }
    
    def _get_shapes(self, labels_shape, output_shape, atlas_res, target_res, output_div_by_n):
        """Calculate cropping and output shapes."""
        # This implements the same logic as the original get_shapes function
        # Reformat resolutions to lists
        atlas_res = utils.reformat_to_list(atlas_res)
        n_dims = len(atlas_res)
        target_res = utils.reformat_to_list(target_res)
        
        # Get resampling factor
        if atlas_res != target_res:
            resample_factor = [atlas_res[i] / float(target_res[i]) for i in range(n_dims)]
        else:
            resample_factor = None
        
        # Output shape specified, need to get cropping shape, and resample shape if necessary
        if output_shape is not None:
            output_shape = utils.reformat_to_list(output_shape, length=n_dims, dtype='int')
            
            # Make sure that output shape is smaller or equal to label shape
            if resample_factor is not None:
                output_shape = [min(int(labels_shape[i] * resample_factor[i]), output_shape[i]) for i in range(n_dims)]
            else:
                output_shape = [min(labels_shape[i], output_shape[i]) for i in range(n_dims)]
            
            # Make sure output shape is divisible by output_div_by_n
            if output_div_by_n is not None:
                tmp_shape = [utils.find_closest_number_divisible_by_m(s, output_div_by_n) for s in output_shape]
                if output_shape != tmp_shape:
                    print('output shape {0} not divisible by {1}, changed to {2}'.format(output_shape, output_div_by_n, tmp_shape))
                    output_shape = tmp_shape
            
            # Get cropping and resample shape
            if resample_factor is not None:
                cropping_shape = [int(np.around(output_shape[i]/resample_factor[i], 0)) for i in range(n_dims)]
            else:
                cropping_shape = output_shape
        
        # No output shape specified, so no cropping unless label_shape is not divisible by output_div_by_n
        else:
            # Make sure output shape is divisible by output_div_by_n
            if output_div_by_n is not None:
                
                # If resampling, get the potential output_shape and check if it is divisible by n
                if resample_factor is not None:
                    output_shape = [int(labels_shape[i] * resample_factor[i]) for i in range(n_dims)]
                    output_shape = [utils.find_closest_number_divisible_by_m(s, output_div_by_n) for s in output_shape]
                    cropping_shape = [int(np.around(output_shape[i] / resample_factor[i], 0)) for i in range(n_dims)]
                # If no resampling, simply check if image_shape is divisible by n
                else:
                    cropping_shape = [utils.find_closest_number_divisible_by_m(s, output_div_by_n) for s in labels_shape]
                    output_shape = cropping_shape
            
            # If no need to be divisible by n, simply take cropping_shape as image_shape, and build output_shape
            else:
                cropping_shape = labels_shape
                if resample_factor is not None:
                    output_shape = [int(cropping_shape[i] * resample_factor[i]) for i in range(n_dims)]
                else:
                    output_shape = cropping_shape
        
        return cropping_shape, output_shape


def labels_to_image_model(labels_shape,
                          n_channels,
                          generation_labels,
                          output_labels,
                          n_neutral_labels,
                          atlas_res,
                          target_res,
                          output_shape=None,
                          output_div_by_n=None,
                          flipping=True,
                          aff=None,
                          scaling_bounds=0.2,
                          rotation_bounds=15,
                          shearing_bounds=0.012,
                          translation_bounds=False,
                          nonlin_std=3.,
                          nonlin_scale=.0625,
                          randomise_res=False,
                          max_res_iso=4.,
                          max_res_aniso=8.,
                          data_res=None,
                          thickness=None,
                          bias_field_std=.5,
                          bias_scale=.025,
                          return_gradients=False):
    """
    Factory function to create LabelsToImageModel with same interface as original.
    
    Returns a PyTorch model that generates synthetic images from label maps.
    """
    
    model = LabelsToImageModel(
        labels_shape=labels_shape,
        n_channels=n_channels,
        generation_labels=generation_labels,
        output_labels=output_labels,
        n_neutral_labels=n_neutral_labels,
        atlas_res=atlas_res,
        target_res=target_res,
        output_shape=output_shape,
        output_div_by_n=output_div_by_n,
        flipping=flipping,
        aff=aff,
        scaling_bounds=scaling_bounds,
        rotation_bounds=rotation_bounds,
        shearing_bounds=shearing_bounds,
        translation_bounds=translation_bounds,
        nonlin_std=nonlin_std,
        nonlin_scale=nonlin_scale,
        randomise_res=randomise_res,
        max_res_iso=max_res_iso,
        max_res_aniso=max_res_aniso,
        data_res=data_res,
        thickness=thickness,
        bias_field_std=bias_field_std,
        bias_scale=bias_scale,
        return_gradients=return_gradients
    )
    
    return model