# Data configuration
data:
  data_dir: "data/processed"
  train_csv: "data/train.csv"
  val_csv: "data/val.csv"
  test_csv: "data/test.csv"
  image_key: "image"
  age_key: "age"
  cache_dir: "data/cache"
  num_workers: 4

# Model configuration
model:
  type: "sfcn"  # Options: sfcn, resnet3d, efficientnet3d
  in_channels: 1
  dropout_rate: 0.3
  use_attention: false

# Domain randomization configuration
domain_randomization:
  augmentation_strength: "medium"  # Options: light, medium, strong
  intensity_range: [0.3, 1.0]
  gamma_range: [0.8, 1.2]
  contrast_range: [0.8, 1.2]
  enable_spatial: true
  scaling_range: [0.9, 1.1]
  rotation_range: 10.0
  nonlinear_std: 2.5
  enable_simulation: true
  resolution_range: [1.0, 2.5]
  anisotropy_range: [1.0, 3.0]
  enable_artifacts: true
  bias_field_range: [0.0, 0.4]
  noise_range: [0.0, 0.07]
  max_augmentations_per_sample: 5

# Training configuration
training:
  batch_size: 8
  epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.00001
  optimizer: "adamw"  # Options: adam, adamw, sgd, rmsprop
  scheduler: "cosine"  # Options: cosine, plateau, onecycle, step, none
  scheduler_params:
    T_max: 100
    eta_min: 0.000001
  loss: "huber_mae"  # Options: mse, mae, huber, huber_mae, weighted_mse
  loss_params:
    delta: 1.0
    mae_weight: 0.5
  early_stopping_patience: 10
  gradient_accumulation_steps: 1
  use_amp: true

# Output configuration
output:
  checkpoint_dir: "checkpoints"
  log_dir: "logs"
  experiment_name: null  # Will be auto-generated if null

# Weights & Biases configuration
wandb:
  use_wandb: true
  project: "brain-age-prediction"
  entity: null

# Miscellaneous
seed: 42
device: null  # Will use CUDA if available, otherwise CPU 